name: flutter_rick_morty
description: RickVerse&MortyVerse
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  english_words: ^4.0.0
  provider: ^6.0.0

  #firebase
  firebase_core: ^1.17.0
  firebase_auth: ^3.3.17
  firebase_storage: ^10.2.15
  firebase_database: ^9.0.13
  google_sign_in: ^5.3.1

  # Api Rest
  retrofit: ^3.0.1+1

  #animations
  flutter_staggered_animations: ^1.0.0
  animations: ^2.0.2

  # State Management.
  flutter_bloc: ^7.2.0
  get_it: ^7.2.0
  shimmer: ^2.0.0

  #Camera
  image_picker: ^0.8.1+3

  #Utils.
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.0
  font_awesome_flutter: ^10.1.0
  url_launcher: ^6.0.18
  equatable: ^2.0.3
  dartz: ^0.10.1
  shared_preferences: ^2.0.13
  internet_connection_checker: ^0.0.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # Api Rest: dio client generator.
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.10
  json_serializable: ^6.2.0

  #Implements images in all the platforms
  flutter_native_splash: ^2.1.6
  flutter_launcher_icons: ^0.9.2
  flutter_app_name: ^0.1.0

flutter_native_splash:
  background_image: "assets/images/splash_screen.png"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.jpeg"

flutter_app_name:
  name: "WikiRick"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/icons/app_icon.jpeg
    - assets/images/Rick_usa.jpg
    - assets/images/detail_view.jpg
    - assets/images/drawer.jpg
    - assets/images/image_error.jpg
  fonts:
    - family: AkayaTelivigala
      fonts:
        - asset: assets/fonts/AkayaTelivigala-Regular.ttf
          weight: 400
